### ISSUE TITLE
Slidemenu events

### ISSUE THREAD

**Issue by m-menon** [unbam/Leaflet.SlideMenu#1]
hi, Thanks for the plugin - seems like the only one of it's kind for leaflet :) Btw a quick question - are there events that I could use - for example when the slidemenu is opened and closed? Moreover is there a method to check if the slidemenu is currently open? Thanks. M.M

**Comment by unbam** [comment]
Question Thank you.
I'm sorry. It does not support now. Implementation is still undecided.

**Comment by m-menon** [comment]
Alright. Thanks anyway for the good work :+1:
