### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by Aditya-Sh** [unbam/Leaflet.SlideMenu#5]
Can we have a bower.json for easy installation to a project? I'll create a pull request if that's alright.

**Comment by unbam** [comment]
Sorry, I have not bower.json.
Would you please pull request.

**Comment by Aditya-Sh** [comment]
Sorry for the delay, got stuck in some other work. I am not able to push a branch, need permissions for contribution.

**Comment by Aditya-Sh** [comment]
Ohh ok. My project uses bower right now. Having a bower.json file would be enough. No need to publish on bower.
